In [1]:
import numpy as np
import torch

In [5]:
data = [
    [1,2],
    [3,4],[5,6]]

x = torch.tensor(data)
print(type(x))

<class 'torch.Tensor'>


In [8]:
np_array = np.array(data)
x_tensor = torch.from_numpy(np_array)
print(x_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)


In [11]:
x_ones = torch.ones_like(x)
print(type(x_ones))

<class 'torch.Tensor'>


In [14]:
zeros = torch.zeros_like(x)
print(zeros)

tensor([[0, 0],
        [0, 0],
        [0, 0]])


In [16]:
random = torch.rand(3,4)
print(random)

tensor([[0.3652, 0.1366, 0.8458, 0.9593],
        [0.6816, 0.8991, 0.4158, 0.5954],
        [0.7338, 0.2147, 0.4015, 0.5644]])


In [18]:
ones_shape = torch.ones(3,4)
print(ones_shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
